### ISSUE TITLE
"Solution" directive throws error in jupyterbook build

### ISSUE THREAD

**Issue by ktyle** [executablebooks/sphinx-exercise#32]
### Describe the problem

Hi, when I attempt to build a Jupyerbook containing a solutions directive as described in [the sphinx-exercise syntax page](https://ebp-sphinx-exercise.readthedocs.io/en/latest/syntax.html), the build fails with the following traceback:

```
Running Jupyter-Book v0.11.2
[etoc] Changing master_doc to 'intro'
Extension error (sphinx_exercise):
Handler <class 'sphinx_exercise.DoctreeResolve'> for event 'doctree-resolved' threw an exception (exception: )
Traceback (most recent call last):
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/domains/std.py", line 1110, in get_fignumber
    return env.toc_fignumbers[docname][figtype][figure_id]
KeyError: 'ex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/events.py", line 111, in emit
    results.append(listener.handler(self.app, *args))
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx_exercise/__init__.py", line 126, in __init__
    self.process(doctree, docname)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx_exercise/__init__.py", line 313, in process
    self._update_linked_node_title(node)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx_exercise/__init__.py", line 154, in _update_linked_node_title
    target_number = self.domain.get_fignumber(
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/domains/std.py", line 1114, in get_fignumber
    raise ValueError from exc
ValueError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/envs/atm433/lib/python3.8/site-packages/jupyter_book/sphinx.py", line 167, in build_sphinx
    app.build(force_all, filenames)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.write(docnames, list(updated_docnames), method)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 534, in write
    self._write_serial(sorted(docnames))
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 541, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 539, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 590, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/sphinx/events.py", line 119, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <class 'sphinx_exercise.DoctreeResolve'> for event 'doctree-resolved' threw an exception (exception: )

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/envs/atm433/bin/jb", line 10, in <module>
    sys.exit(main())
  File "/path/to/envs/atm433/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/envs/atm433/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/path/to/envs/atm433/lib/python3.8/site-packages/jupyter_book/cli/main.py", line 316, in build
    builder_specific_actions(
  File "/path/to/envs/atm433/lib/python3.8/site-packages/jupyter_book/cli/main.py", line 516, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
```

The particular markdown file that contains the solution directive is named `ex.md` in my repository and is linked below.

[ex.md](https://github.com/executablebooks/sphinx-exercise/files/7093607/ex.md)

Thanks!

Kevin

### Link to your repository or website

https://github.com/ktyle/sphinx_exercise_proto

### Steps to reproduce

run 
```
jupyterbook build .
```
in book's top directory

### The version of Python you're using

3.8.10 (also occurs on 3.9.x)

### Your operating system

Linux (also occurs on Mac 11.2 M1)

### Versions of your packages

```
Jupyter Book      : 0.11.2
External ToC      : 0.2.2
MyST-Parser       : 0.13.7
MyST-NB           : 0.12.3
Sphinx Book Theme : 0.1.1
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.3
sphinx-exercise :0.1.1
sphinx: 3.5.4
```

**Comment by ktyle** [comment]
An update: the problem seems to be related to the default behavior of numbering each exercise. If the `:nonumber:` flag is set, the page builds properly. Omitting this flag causes the admonition-like box to be blank (i.e., "Exercise" does not even appear).

**Comment by AakashGfude** [comment]
Thank you @ktyle for the issue, and for explaining how to recreate it. Will make a new release soon with the fix.

**Comment by AakashGfude** [comment]
@ktyle This should be fixed now with the latest release `v0.2.1`. Sorry for the delay.

**Comment by ktyle** [comment]
@AakashGfude Looks good!! Thanks!
